### ISSUE TITLE
Internal Server Error when using CORS

### ISSUE THREAD

**Issue by sharkykh** [trakt/api-help#197]
Hello.
I am getting a HTTP 500 error (on a CORS preflight request) when I try to call any of the endpoints I've tried.
I have Python application and it works fine with similar endpoints.

Endpoints I've tried:
- `/users/me`
- `/sync/playback`
- `/users/me/watching`
- `/oauth/token` (with `grant_type: authorization_code`)

[The API App (on Trakt) is configured correctly](https://user-images.githubusercontent.com/10238474/91518020-e54fcd80-e8f7-11ea-8dac-0cb5cf5e2637.png), and it has been working for the past year.

Here is a HAR of an example API call that my application makes.
I have only redacted my access key and API key from the data.

[trakt.har.zip](https://github.com/trakt/api-help/files/5139801/trakt.har.zip)
(Can be viewed using DevTools or [HAR Analyzer](https://toolbox.googleapps.com/apps/har_analyzer/))

The console prints out the following errors:
- `sharkykh.github.io/:1	Access to fetch at 'https://api.trakt.tv/users/me' from origin 'https://sharkykh.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`
- `api.trakt.tv/users/me:1	Failed to load resource: net::ERR_FAILED`

Also, the `x-error-message` response headers specifically says:
`Internal server error. Please open a support issue and include your full API request and response, including all headers.`

**Comment by EmreYYZ** [comment]
My website was working fine before the scheduled maintenance that took place yesterday. However, now I am getting a CORS error. I updated my app's Origin information (a couple of hours ago) from the settings on Trakt.tv with the appropriate domain information, however, I am still getting the error.

My app has a simple GET request:

```function getInfo() {
  var request = new XMLHttpRequest();

  request.open('GET', `https://api.trakt.tv/shows/the-office/seasons/${seasonNo}/episodes/${episodeNo}?extended=full`);

  request.setRequestHeader('Content-Type', 'application/json');
  request.setRequestHeader('trakt-api-version', '2');
  request.setRequestHeader('trakt-api-key', '0000000000000000000000000000000000000000000');

  request.onreadystatechange = function () {
    if (this.readyState === 4 && this.status == 200) {
      var response = JSON.parse(this.responseText);
      document.getElementById('title').innerHTML = response.title;
      document.getElementById('runtime').innerHTML = `${response.runtime} mins.`;
      document.getElementById('rating').innerHTML = `${(response.rating).toFixed(1)}/10`;
      document.getElementById('seasonInfo').innerHTML = response.season;
      document.getElementById('episodeInfo').innerHTML = response.number;
      document.getElementById('overview').innerHTML = response.overview;
      var element = document.getElementById("info");

      if (element.classList.contains('hidden') == true) {
        element.classList.toggle('hidden');
        // remove loader
      }
    }
  };
  request.send();
}
```
Here are the errors I get from the console:

```Access to XMLHttpRequest at 'https://api.trakt.tv/shows/the-office/seasons/6/episodes/17?extended=full' from origin 'https://randommifflin.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.```

```main.js:151 GET https://api.trakt.tv/shows/the-office/seasons/6/episodes/17?extended=full net::ERR_FAILED```

```Unchecked runtime.lastError: The message port closed before a response was received.```

**Comment by rectifyer** [comment]
I just pushed some CORS related fixes, please let me know if it works ok now.

**Comment by sharkykh** [comment]
@rectifyer Thank you very much!
Just tested and it works once again :)

**Comment by pouyio** [comment]
For me, endpoints, like `/oauth/token` started working again, but still having the same CORS problem with some others, to mention a few:
- `/sync/watchlist/shows`
- `/shows/${id}/people` and `movies`
- `/shows/${id}/ratings` and `movies`

Even some others fail randomly i.e `/movies/watched/weekly` and `shows`. All requests are done from web.

Still thanks for the great work and quick response 😃

**Comment by sttz** [comment]
I'm also encountering this issue, `/scrobble/pause` endpoint returns a 500 Internal Server Error on the OPTIONS request.

Here are the request/response details: [trakt_scrobble_pause.har.zip](https://github.com/trakt/api-help/files/5145935/trakt_scrobble_pause.har.zip)

**Comment by rectifyer** [comment]
Ok, this should work now. It appears one of the API servers didn't have this code change. That's why it would mostly work, but then sometimes not work. In any case, I redeployed the fix to all API servers and it seems consistent now.

**Comment by sharkykh** [comment]
Hi again.
It worked fine when you commented, and for a while after.
I checked again right now and I'm getting the same errors, still inconsistently (for me it's kind of a 50%/50% chance).

[Here is an updated HAR.](https://github.com/trakt/api-help/files/5146465/trakt.zip)
But it seems like the same exact error when it happens.

Thank you for looking into this issue! 👍

**Comment by rectifyer** [comment]
There was an issue with auto scaling, so most servers had the correct code change, but a few didn't. That's why it mostly worked, but sometimes didn't. It should be all ok now and I confirmed that adding a new server has the correct code change. Closing this issue, but please let me know if you see any further issues.
