### ISSUE TITLE
Apple Login Error: "lat invalid"

### ISSUE THREAD

**Issue by javikr** [trakt/api-help#402]
There is an issue with the login using the Apple Sign-In from the Trakt iOS login screen.

The login always fails with the following error message: 

`Could not authenticate you from Apple because "lat invalid`

This error happens using third party apps and also Trakt app. 

Our app was rejected by Apple due to this issue. Please, could you check it?

Please advice.

**Comment by javikr** [comment]
It is also failing the login with Google with the following error:

`There was an error during the transport or processing of this request. Error code = 103, Path = /v3/signin/_/AccountsSignInUi/data/batchexecute`

Hope this helps.

**Comment by rectifyer** [comment]
I pushed a potential fix for Apple sign in. I'm not sure what that Google error means, that isn't an error or path on the Trakt side.

**Comment by javikr** [comment]
Thank you for your work, but it seems that something is still not working as expected with the Apple Sign In. When I logging using the Apple Sign In flow, the app opens the profile screen of the Trakt website. It doesn't redirect to the app itself. 

It happens with every 3rd party app using the Trakt API and also with the Trakt official app.

Please advice,

**Comment by rectifyer** [comment]
Good catch, sorry about that! I just pushed another fix and verified with the Trakt app that Apple sign in redirects correctly.

**Comment by rectifyer** [comment]
@javikr did your app get approved with the Apple sign in fix?

**Comment by javikr** [comment]
@rectifyer yes, but now they are rejecting us due to the cookie prompt that appears on the login flow site. As this is an issue that is eligible to be resolved on the next update, they have proceeded with it, but I'm pretty sure that they are going to reject it again :(

Here is the App Review Team message:

> Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing
> 
> 
> We noticed your app accesses web content you own where you collect cookies. Cookies may be used to track users, but you do not use App Tracking Transparency to request the user's permission before collecting data used to track.
> 
> Starting with iOS 14.5, apps on the App Store need to receive the user’s permission through the AppTrackingTransparency framework before collecting data used to track them.
> 
> Next Steps
> 
> If you do not collect cookies for tracking purposes on iOS, remove the cookie prompts or revise them to clarify you do not track users.
> 
> Otherwise, follow these steps to resolve this issue:
> 
> 1. If you haven't already, [update your app privacy information in App Store Connect](https://developer.apple.com/help/app-store-connect/manage-app-information/manage-app-privacy) to disclose that you track users. You must have the [Account Holder or Admin role](https://developer.apple.com/support/roles/) to update app privacy information.
> 2. Implement [App Tracking Transparency](https://developer.apple.com/documentation/apptrackingtransparency).
> 3. Request permission using App Tracking Transparency before collecting data used to track the user. When you resubmit, indicate in the Review Notes where the permission request is located.
> 4. If the user does not allow tracking, do not collect cookies for tracking purposes.
> 
> You may also choose to remove the tracking functionality from your app, including tracking that occurs when accessing web content.

I have reply their message explaining that we have no control over third party cookies, but with no success... They are still rejecting it. 

Hope this helps.

**Comment by rectifyer** [comment]
Hmm, that's an interesting one. It's true we use cookies, but not to track anyone or sell their data (like Apple might assume). As with any standard web sign in form, we use cookies to establish a logged in session. I'll look into this more, but I'm not sure we can simply not use cookies and have the OAuth flow function as it needs to.

**Comment by javikr** [comment]
Thank you. I will keep you informed if they rejected us again ;)

**Comment by javikr** [comment]
Just to inform that Apple approved the version without any change in our code... I'm pretty sure it depends on the person who is reviewing the app. Thank you for your help ;)
